title: Jessica Chen
logo: /assets/img/profile_pic.jpg
description:  jessicachen at nyu dot edu
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
exclude:
  - LICENSE
  - README.md
  - template.md